<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>WolverineApp</RootNamespace>
    <AssemblyName>Order.WebApi</AssemblyName>
    <UserSecretsId>order-framework-webapi</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Order.Application\Order.Application.csproj" />
    <ProjectReference Include="..\Order.Infrastructure\Order.Infrastructure.csproj" />
    <ProjectReference Include="..\Order.ServiceDefaults\Order.ServiceDefaults.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" PrivateAssets="all" />
    <PackageReference Include="Mapster" />
    <PackageReference Include="Mapster.DependencyInjection" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="WolverineFx" />
    <PackageReference Include="WolverineFx.FluentValidation" />
    <PackageReference Include="WolverineFx.RuntimeCompilation" />
  </ItemGroup>
</Project>
